-- 코드를 입력하세요
WITH DDAY AS (
    SELECT APNT_NO, PT_NO, MCDP_CD, MDDR_ID, APNT_YMD
    FROM APPOINTMENT
    WHERE DATE_FORMAT(APNT_YMD, '%Y-%m-%d') = '2022-04-13' 
        AND MCDP_CD = 'CS'
        AND APNT_CNCL_YN = 'N'
    
),
CTE AS (
    SELECT DDAY.APNT_NO, PATIENT.PT_NAME, PATIENT.PT_NO, DOCTOR.MCDP_CD, DOCTOR.DR_NAME, APNT_YMD
    FROM DDAY
    JOIN DOCTOR
    ON DOCTOR.DR_ID = DDAY.MDDR_ID
    JOIN PATIENT
    ON PATIENT.PT_NO = DDAY.PT_NO
)
SELECT *
FROM CTE
ORDER BY APNT_YMD ASC