-- 코드를 입력하세요
WITH NOTAVAILABLE AS (
    SELECT DISTINCT CAR_ID 
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE END_DATE >= '2022-11-01' AND START_DATE < '2022-12-01'
),
SEDAN AS (
    SELECT DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE CAR_TYPE = "세단" AND DURATION_TYPE = "30일 이상"
),
SUV AS (
    SELECT DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE CAR_TYPE = "SUV" AND DURATION_TYPE = "30일 이상"
)
SELECT *
FROM (
    SELECT CAR_ID, CAR_TYPE,
    CASE CAR_TYPE
    WHEN "세단" THEN FLOOR((DAILY_FEE * 30 * (100 - (SELECT DISCOUNT_RATE FROM SEDAN))) / 100)
    WHEN "SUV" THEN FLOOR((DAILY_FEE * 30 * (100 - (SELECT DISCOUNT_RATE FROM SUV))) / 100)
    END AS FEE
    FROM CAR_RENTAL_COMPANY_CAR
    WHERE CAR_ID NOT IN (SELECT * FROM NOTAVAILABLE) AND CAR_TYPE IN ("세단", "SUV") AND (
        90
    
    )
    ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC
) AS A
WHERE A.FEE BETWEEN 500000 AND 1999999