-- 코드를 작성해주세요
WITH FRONTEND AS (SELECT SUM(`CODE`) AS `CODE` FROM SKILLCODES WHERE CATEGORY = "Front End"),
PYTHON AS (SELECT `CODE` FROM SKILLCODES WHERE NAME = "Python"),
CSHARP AS (SELECT `CODE` FROM SKILLCODES WHERE NAME = "C#")
SELECT CASE
WHEN SKILL_CODE & (SELECT `CODE` FROM FRONTEND) > 0 AND 
SKILL_CODE & (SELECT `CODE` FROM PYTHON) >= (SELECT `CODE` FROM PYTHON) THEN "A"
WHEN SKILL_CODE & (SELECT `CODE` FROM CSHARP) >= (SELECT `CODE` FROM CSHARP) THEN "B"
WHEN SKILL_CODE & (SELECT `CODE` FROM FRONTEND) > 0 THEN "C"
END AS `GRADE`, ID, EMAIL
FROM DEVELOPERS
WHERE (CASE
WHEN SKILL_CODE & (SELECT `CODE` FROM FRONTEND) > 0 AND 
SKILL_CODE & (SELECT `CODE` FROM PYTHON) >= (SELECT `CODE` FROM PYTHON) THEN "A"
WHEN SKILL_CODE & (SELECT `CODE` FROM CSHARP) >= (SELECT `CODE` FROM CSHARP) THEN "B"
WHEN SKILL_CODE & (SELECT `CODE` FROM FRONTEND) > 0 THEN "C" END) IS NOT NULL
ORDER BY `GRADE` ASC, ID ASC