-- 코드를 작성해주세요
SELECT B.ID AS ID, B.GENOTYPE AS GENOTYPE, A.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA as A INNER JOIN ECOLI_DATA as B
ON A.ID = B.PARENT_ID
WHERE A.GENOTYPE & B.GENOTYPE = A.GENOTYPE
ORDER BY ID ASC