-- 코드를 입력하세요
WITH B AS (SELECT CAR_ID FROM (SELECT CAR_ID, 
CASE
WHEN "2022-10-16" BETWEEN START_DATE AND END_DATE THEN "대여중"
ELSE "대여 가능" END AS AVAILABIlITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY) AS A WHERE A.AVAILABILITY = "대여중")
SELECT DISTINCT CAR_ID,
CASE
WHEN CAR_ID IN (SELECT CAR_ID FROM B) THEN "대여중"
ELSE "대여 가능" END AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
ORDER BY CAR_ID DESC


-- 다른 풀이
SELECT 
CAR_ID,
CASE 
    WHEN MAX('2022-10-16' BETWEEN START_DATE AND END_DATE) = 1 THEN '대여중'
    ELSE '대여 가능'
END AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
ORDER BY 1 DESC
출처: https://20240228.tistory.com/248 [지적 겸손함:티스토리]

-- 다른 풀이
SELECT 
    CAR_ID, 
    CASE
        WHEN COUNT(CASE 
                    WHEN START_DATE <= '2022-10-16' AND END_DATE >= '2022-10-16'
                    THEN 1 ELSE NULL 
                   END) = 0 
        THEN '대여 가능' ELSE '대여중' 
    END AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
ORDER BY CAR_ID DESC