-- 코드를 작성해주세요
SELECT A.ITEM_ID, B.ITEM_NAME, B.RARITY
FROM
(SELECT ITEM_TREE.ITEM_ID FROM
ITEM_TREE JOIN ITEM_INFO ON ITEM_TREE.PARENT_ITEM_ID = ITEM_INFO.ITEM_ID WHERE ITEM_INFO.RARITY = "RARE") AS A 
JOIN ITEM_INFO AS B
ON A.ITEM_ID = B.ITEM_ID
ORDER BY A.ITEM_ID DESC