-- 코드를 입력하세요
SELECT A.PRODUCT_CODE, A.PRICE*B.TOTAL_AMOUNT AS SALES
FROM PRODUCT AS A JOIN (
    SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS TOTAL_AMOUNT
    FROM OFFLINE_SALE
    GROUP BY PRODUCT_ID
) AS B ON A.PRODUCT_ID = B.PRODUCT_ID
ORDER BY SALES DESC, A.PRODUCT_CODE ASC