-- 코드를 입력하세요
SET @HOUR = -1;
WITH COUNTS AS (
    SELECT hour(DATETIME) AS HOUR, COUNT(*) AS COUNT
    FROM ANIMAL_OUTS
    GROUP BY hour(DATETIME)
    ORDER BY HOUR 
),
HOURS AS (
    SELECT (@HOUR := @HOUR +1) AS HOUR
    FROM ANIMAL_OUTS
    WHERE @HOUR < 23
)
SELECT HOURS.HOUR, IFNULL(COUNTS.COUNT, 0) AS COUNT
FROM HOURS
LEFT JOIN COUNTS
ON HOURS.HOUR = COUNTS.HOUR
ORDER BY HOURS.HOUR