-- 코드를 작성해주세요
SELECT ITEM_INFO.ITEM_ID, ITEM_INFO.ITEM_NAME
FROM
(SELECT ITEM_ID
FROM ITEM_TREE 
WHERE PARENT_ITEM_ID IS NULL ) AS A
JOIN ITEM_INFO ON A.ITEM_ID = ITEM_INFO.ITEM_ID
ORDER BY ITEM_ID ASC