WITH DURATION AS (
    SELECT HISTORY_ID, DATEDIFF(END_DATE, START_DATE) + 1 AS DURATION, CAR_RENTAL_COMPANY_CAR.DAILY_FEE AS DAILY_FEE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY JOIN CAR_RENTAL_COMPANY_CAR
    ON CAR_RENTAL_COMPANY_RENTAL_HISTORY.CAR_ID = CAR_RENTAL_COMPANY_CAR.CAR_ID
    WHERE CAR_RENTAL_COMPANY_CAR.CAR_TYPE = "트럭"
),
OVER7 AS (
    SELECT DISCOUNT_RATE 
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN 
    WHERE CAR_TYPE = "트럭" AND DURATION_TYPE = "7일 이상"
),
OVER30 AS (
    SELECT DISCOUNT_RATE 
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN 
    WHERE CAR_TYPE = "트럭" AND DURATION_TYPE = "30일 이상"
),
OVER90 AS (
    SELECT DISCOUNT_RATE 
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN 
    WHERE CAR_TYPE = "트럭" AND DURATION_TYPE = "90일 이상"
)
SELECT HISTORY_ID, FLOOR(DURATION * DAILY_FEE * (100 - (
    CASE
        WHEN DURATION >= 90 THEN (SELECT DISCOUNT_RATE FROM OVER90)
        WHEN DURATION >= 30 THEN (SELECT DISCOUNT_RATE FROM OVER30)
        WHEN DURATION >= 7 THEN (SELECT DISCOUNT_RATE FROM OVER7)
        ELSE 0 END
)) / 100) AS FEE
FROM DURATION
ORDER BY FEE DESC, HISTORY_ID DESC