-- 코드를 입력하세요
WITH RANKING AS (
    SELECT *, rank() OVER (PARTITION BY CATEGORY ORDER BY PRICE DESC) AS RANKING
    FROM FOOD_PRODUCT
)
SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
FROM RANKING
WHERE CATEGORY IN ('과자', '국', '김치', '식용유') AND RANKING = 1
GROUP BY CATEGORY
ORDER BY MAX_PRICE DESC