-- 코드를 입력하세요
WITH ONSALE AS (
    SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
    FROM ONLINE_SALE
    WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-03'
),
OFFSALE AS (
    SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT
    FROM OFFLINE_SALE
    WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') LIKE '%2022-03%'
)
SELECT * FROM ONSALE UNION SELECT * FROM OFFSALE ORDER BY SALES_DATE ASC, PRODUCT_ID ASC, USER_ID ASC