-- 코드를 작성해주세요
WITH RECURSIVE CTE AS (
    SELECT ID, 
        1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT E.ID, CTE.GENERATION + 1 AS GENERATION
    FROM ECOLI_DATA as E
    JOIN CTE
    ON CTE.ID = E.PARENT_ID
)
SELECT ID 
FROM CTE
WHERE GENERATION = 3
ORDER BY ID