-- 코드를 작성해주세요
SELECT ITEM_ID, ITEM_NAME, RARITY
FROM (
SELECT PARENT_ITEM_ID
FROM ITEM_TREE
GROUP BY PARENT_ITEM_ID ) AS A
RIGHT JOIN ITEM_INFO AS B
ON A.PARENT_ITEM_ID = B.ITEM_ID
WHERE PARENT_ITEM_ID IS NULL
ORDER BY ITEM_ID DESC