-- 코드를 작성해주세요
WITH RECURSIVE RECUR AS (
    SELECT ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT ECOLI_DATA.ID, RECUR.GENERATION + 1 AS GENERATION
    FROM ECOLI_DATA
    JOIN RECUR
    ON RECUR.ID = ECOLI_DATA.PARENT_ID
),
CHILDS AS (
    SELECT COUNT(*) AS NUMCHILD, PARENT_ID AS ID
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NOT NULL
    GROUP BY PARENT_ID
)
SELECT COUNT(*) AS COUNT, GENERATION
FROM CHILDS
RIGHT JOIN RECUR
ON RECUR.ID = CHILDS.ID
WHERE NUMCHILD IS NULL
GROUP BY GENERATION
