-- 코드를 입력하세요
SELECT A.USER_ID, A.NICKNAME, B.TOTAL_SALES
FROM USED_GOODS_USER AS A
RIGHT JOIN
(SELECT WRITER_ID, SUM(PRICE) AS TOTAL_SALES
    FROM USED_GOODS_BOARD
    WHERE STATUS = "DONE"
    GROUP BY WRITER_ID
    HAVING SUM(PRICE) >= 700000) AS B
ON B.WRITER_ID = A.USER_ID
ORDER BY B.TOTAL_SALES