-- 코드를 작성해주세요
WITH AVGSCORE AS (
    SELECT EMP_NO, 
    CASE
    WHEN AVG(SCORE) >= 96 THEN "S"
    WHEN AVG(SCORE) >= 90 THEN "A"
    WHEN AVG(SCORE) >= 80 THEN "B"
    ELSE "C" END AS GRADE
    FROM HR_GRADE
    GROUP BY EMP_NO
)
SELECT HR_EMPLOYEES.EMP_NO, EMP_NAME, AVGSCORE.GRADE,
CASE AVGSCORE.GRADE
WHEN "S" THEN SAL * 0.2
WHEN "A" THEN SAL * 0.15
WHEN "B" THEN SAL * 0.1
ELSE 0 END AS BONUS
FROM HR_EMPLOYEES JOIN AVGSCORE
ON HR_EMPLOYEES.EMP_NO = AVGSCORE.EMP_NO
ORDER BY EMP_NO ASC