-- 코드를 작성해주세요
SELECT D.DEPT_ID, DEPT_NAME_EN, SAL.AVG_SAL 
FROM
(SELECT ROUND(AVG(SAL)) AS AVG_SAL, DEPT_ID
FROM HR_EMPLOYEES
GROUP BY DEPT_ID) AS SAL
JOIN
HR_DEPARTMENT AS D
ON D.DEPT_ID = SAL.DEPT_ID
ORDER BY SAL.AVG_SAL DESC